# Global mod engine configuration
[modengine]
# If true then the debug console will appear as .exe is running
debug = false

# Mod loader configuration
[extension.mod_loader]
enabled = true

# Not currently supported for Elden Ring
loose_params = false

# List of directories that contain modded files in order of prioritization. 
# Each specified mod directory must match the game assets within Fromsoft's asset structure. 
# If you mod parts/something.partsbnd.dcx, the modded version must be at mod/parts/something.partsbnd.dcx.
#
# Absolute paths to mods must use '\\' to separate path items. 
# If your mod is at E:\coolstuff\coolmod, write the path as "E:\\coolstuff\\coolmod".
#
# If there's no drive specifier (C:, D:, etc), the path is relative to where the launcher is located. 
# modengine 2 will look for the directory mod inside the mod engine 2 directory with the launcher.
#
# Multiple mods must be separated with commas. For example if you have 3 mods use:
# mods = [
#    { enabled = true, name = "coolmod", path = "mod1" },
#    { enabled = true, name = "nicemod", path = "mod2" },
#    { enabled = true, name = "sosomod", path = "mod3" }
# ]
# Note modengine 2 cannot resolve conflicting files including regulation.bin, the mod with the highest priority will be the file loaded. 

mods = [
    { enabled = true, name = "default", path = "bingo" }
]

# When enabled, scylly hide will be injected into the game. This allows for antidebug measures in the game to be bypassed so that you can attach
# debuggers to the game without as much trouble. If you're not reverse engineering the game, this option is probably not for you.
[extension.scylla_hide]
enabled = false